<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Entire Approval Flow Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>05c38171-0874-4d30-a800-e149211b0c20</testSuiteGuid>
   <testCaseLink>
      <guid>41bebf67-b312-420a-8bb0-e9e8ff1358d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>977c5384-f5fa-4174-b9fe-00d77e2a807e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from burger menu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29539a93-417d-47bf-b0e9-10b6c0f63ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a15d660-8462-40da-a55c-490e76a91edf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e785d9-a2a0-4d77-946c-e3d99bc35ac3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba5c3595-39a4-4145-a3bd-2fad936e2770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from Dashboard bottom button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daa645d1-c041-4700-bc63-c33c951feed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e2c8af-8cfd-4fbb-add6-f205bb553b51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfea876-c7d0-41ec-ae8e-28610080766f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b92fd869-4458-40b6-9c11-37484304be9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6944eb-5c0b-4fd4-b5cb-be18fba7ffef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e117557-129d-4dd7-9f68-ec25a105b521</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9846dda6-f143-4795-ae5e-43d15b523b6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b724b943-7d60-4258-9bfb-7f54e7ff3d6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c30ed68f-c04d-4551-ac7f-dd06b898d011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85559751-e90a-4aec-b8e6-fe119ea16571</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e016ad-fd6d-4800-b47e-ea39f590f8b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3f0e8f4-bfb3-4bb3-96e0-95e2e684bd4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf8b6449-12a5-4494-aa3b-8031ca7074b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc6bca0-c3ad-4c30-912b-c2f62ed1e8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fb63c8f-41e4-40ec-b85c-bbf4f9bbb158</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6951a439-e8d3-44bf-ad50-405cd11d8840</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823fd51e-e6d3-4816-972e-43e3ee8bb59d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6009164-ecb6-45de-80a5-efb8ea20fae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81dd6383-a970-471d-b578-0b95ac1b9275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bc324e8-b986-4b36-b076-c2bc0b87c213</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f52e6bd7-9e64-448f-88fe-a60340f0e307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68f625f-0dc8-4266-945d-c507a36b985b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d195309c-9de5-4df4-8e72-a33a4108fe05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e93c0912-6bd9-4c3e-a9c7-432f96922918</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d282e9b9-5b65-4a42-a645-8c05773c0a66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8c2a513-ba18-489a-8666-5abc6f77fe31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>527cc230-ceb0-4738-bc02-360923063430</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d828a5cf-e72c-4612-a5bb-f7eff4918a83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eed3987-39a3-4bbc-9321-323c417e3bfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f7d6a47-983a-4ab4-9405-874fc59c0fd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c1b5ce-44a1-48a9-b53e-80fff18211fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c3bf91a-5646-40d7-be50-b301c8fb5ed5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288c30f9-eeea-4842-a351-ea5297897586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d45a9a-fd4c-4502-9294-205852b29214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0530d7-48fc-49e9-bc04-fdc392c245d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7feaab21-8762-4778-b8ea-9f253fe1de08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d58f2b1-7e42-4d03-bee3-62e9fa283a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65598a8-cebc-4c62-8e29-9e1d15cf3f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e3eabe-7cec-4daf-b26c-b62db914717b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3966b560-6212-4d9f-a09b-0c3a3032e6d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dd448f3-7f5e-4978-b1c3-3f59f7bd2014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe6907e-8a53-402f-9443-aaa6311844d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abe4f6b-8ba0-4ff2-8b04-e1c331437074</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db84f4d2-2ee5-4e21-bb7b-f75dfd07131f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>898260f7-d217-4256-8c4c-f26df7b609e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b19755c-ad99-4c4e-8b9a-d52e1b0c017c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f1ac89c-96a0-4d9a-ba68-7c584050edc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2af19a4-e1d1-4771-a064-c3b438ddc885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8924610-c7e7-43ea-8dab-4e45ed64c520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cfa752-2977-47eb-b943-1fe547aa25ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452f5c07-7e6d-4a63-9cfa-5860c53a6db9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e6cefde-b83f-4363-ad99-d093aac9630e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5f80293-3ea5-4fcc-afc0-45bff68df807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d6fea8b-1e9f-4500-8a54-b78ab60c2cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7db8be4-75b7-44a6-99e5-3f112fcfa10f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0ba9c4a-9900-407c-9085-ed39f76fa38a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20dfcbe-cd47-40ad-92e5-0c2355497ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d16fba9-74c5-454f-8f9c-4ff0977b3480</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a8f42d-3aa2-4d36-88aa-6383e828bf1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4831fe42-7a10-41b6-8660-6c4a6813bdcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a966c47-82f5-4c63-98e0-6dd56c0784c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6005fd0d-295a-4f11-8653-f7414f308143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84d725f-dbc2-480d-a705-8d57c46cbc64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0f3c83c-3cdc-4269-913d-67c2fa26567d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b29267-35fe-4a53-91f9-46f5b5b55121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d88669d-ee6d-4ba0-b2d5-97b841e64a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a6d77ea-70a7-4b00-9e46-ac874a7f1ebc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7e0a62a-c116-4cb1-a964-1beea24ab325</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8023b025-c9d6-46d6-bc2c-06d5ac3be4e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b24996-bf12-4443-8faa-a0c46f7995f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c02284b-642e-492e-9ea1-3eb8b610f37a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63e264dc-b107-4b03-a888-f5caecce0c96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e93cd4e-c3af-4c63-9fd3-d6619cfb616f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1437e41f-7999-4c9a-a547-4c98c8a4f943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b490ea-2b65-41e4-bad8-0e2c3db66ca4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d09bf926-601f-4309-83a4-95bb63c27453</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3452814-0311-4208-9647-1c407ec70497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd42ee8f-00f9-4340-aa6e-a9df7010d891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b21e4b-783f-4b13-8708-38c41c671245</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc31cf54-ff53-43cc-a853-bf07a4740eb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3879a14c-d666-4447-8da9-c2342c15f9bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6a5258b-0482-46f0-abe9-305d3571438a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f77d13-9e2a-4c1f-8a7c-f193bcb1d351</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1483b9b-9cd0-4e30-ac1b-5f57a85301b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f443579-c940-4978-b5d6-b68cf64b685c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1026e239-b837-4602-aefa-d1637be13bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf28faf9-2a1c-43b2-8f1d-465f97d1811a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd047d7f-6bab-44a6-8ba7-2e76366924b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4845520a-fcdb-44a5-b708-38c0a03fe593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e9c875-d714-42e7-a25c-c3ad09ba8c18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82daf827-6ca5-4672-8c0f-f6d7161e357c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c59000cc-b211-4c74-bd6e-fcc5d97514b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da60edf-3c67-4ac7-a639-9e818158179b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ef94b9a-e406-44da-be0e-7a994847b3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ccaba82-30ac-4008-84ff-b69655780237</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c9760f6-1e94-45d5-bb79-2364f0c88ae8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f55b1b7-3ff2-4a9b-9cf4-4a14f5a795b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cf57cb-0b67-493d-abc3-e42a054783a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dbfa71e-f05a-456a-ace4-eb20fa35b80e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>442ba885-e15b-465f-912c-6ef9ab31c021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849088c8-b028-4cc3-8278-a34adab897b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c11b3f7d-258d-4478-85f3-05f72f73b2dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>420a82e3-f181-4f1e-ba4b-27646a7628c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cce7fdc2-0be6-42ac-8a06-bb4fcebf487f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d08add-fd5f-4040-ad44-8dc16ef354bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f30b1ff1-24bb-4b78-90fe-1a172d3050cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b1bec1-b956-4006-9886-e7961e1c51ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7eb30201-6ee9-4c75-b4bb-f26b4f9b4609</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1d7aa4f-7a08-415f-a0d0-44d197a8f6db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbdf2ac0-2086-4100-a75f-19876ae902d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fbed9ba-485c-4098-a7da-135804ffae6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24dc841a-8844-4784-8b82-49902e5755ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b9ba2a-42b2-4136-b88f-fa6afbd1d4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c75382-d3d2-41cf-a226-6414d8b39866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be09dd65-549a-400c-9a3a-8fcf47be5867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94272a49-2bcc-44fc-a51d-f1719104ad55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7e0fd1-56d1-463d-a138-febf1a7185d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eddb0eb-2f3a-4cce-8bbf-4eb94cedde2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bb15204-41c0-4e14-98e0-ceae28e76bc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bc2627e-dd79-4535-810b-c60b10424d82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b95ce6d2-0152-4f00-a9e2-f88304082c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05830ecd-35df-4bce-b10e-92a352999129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee991d7d-3c4a-4016-9790-7178a2f8617d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d51a13f6-7caf-40bc-97f9-4e710162e4c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371bf4eb-4d60-4939-b2b3-05777f01dd57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47db51cc-a80e-4435-8327-7b49fbd1f6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40f3653-a31e-467b-8d35-a1172195192a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8519346b-b16d-41ac-8824-28e397725c48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b6017c-b6c5-4af3-bd0a-8fe4c3644a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ed6feb-72d3-435e-b2b0-19d299aa7ded</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd796fb7-7c7f-434d-bf1e-ae7307642b31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b1b87df-e48b-4a6e-94b2-6483e32a762b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0caa56-d3d9-4c54-8f55-a46480f1de9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a076830-6686-4f5b-9897-dd2ea5995c82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b12bf6-4913-4410-bb83-df04c70ea1f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c49f57d9-b68f-48ff-becb-ae4e138d608f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0bf3b9-f003-4a8b-a70d-07b11f7c82a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6460655-5d78-4924-857e-82dd39ac838f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc05dc2-a5bf-4a46-acc5-74a88fe5f330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d39b3ea-eca7-452f-bce1-3a51f7f4cb04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a946c47-78cf-4cd7-903f-a573cb44b48b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c86eb9c-d08e-45aa-86ac-0eedcca0c52a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e069694f-6e5d-4eb8-ae86-5ad1ec73495e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a5f7bde-53c8-4dc8-984e-ece9d8ae1f53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a9a1cb1-8e23-483b-93c6-ea9a62c05b2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e042d2a-6346-4d7a-bd97-a0976fb35887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1140dfbe-a837-4495-ad63-eddefad6ab30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6adb865d-1ef4-4b0f-bbee-c1a66c89467c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcecb421-3276-48be-a4af-daad57d378e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc7987b-7cc1-483e-aca4-4c34fa7d7361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4479eb9-8831-4187-958a-5ff035d286b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b32a61c0-307f-4f15-85cb-6d8a68fe019e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cfefeb9-2433-40c3-a5f8-66aa1bae33d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b53bb318-e940-4303-aff5-563aca6ea0dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00315e63-a93e-462c-9752-a2d41a2357d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8bfc260-3c80-4bbf-a897-4de4d14818d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d4e955b-18d2-479e-b335-b7845c82bc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01789308-15da-46d4-be8c-65a8cd299012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d782590-a3b0-45c3-ab46-70e3ec76214c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c9be587-c13e-45d7-b183-e7ab6238b596</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ff0a41-aa52-472a-9a1e-76f0bfe4c4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce280073-7969-4923-9ea9-8f67506bad5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab928e9e-cd3b-4421-a6a1-200aa186244b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c84ae3fa-53e5-488a-a510-28a14503dd9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d64a7a-4be6-493c-af3f-a7c82437adcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7395da92-24ef-476a-b62d-abec0ce8acc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a92cd9-f04d-4e07-8d19-c6682396400d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccefe629-352b-40de-85f7-6b4ec6f1822f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>add06736-d363-4232-ac32-1fd728cafc88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80098733-7e58-4d49-aa89-75c5b05130a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8b14de3-f291-4a6e-b74f-f2ec8a552c2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23a58c4c-c334-43f4-a6c6-6f9526acddf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0980ecda-830f-4794-b936-1ef7cecfde1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9e22ae-4863-44d8-a4ea-dcf687b80b14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f876e5c-31f6-49ef-8fe6-5a7510b6a4eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0df7dd78-91e3-47e4-a742-7e6e718902ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df00eed-253a-40d7-bff0-924ecbcaf440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4413d35c-9ec7-4fec-8a71-a22a226be244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccdccb28-2230-417a-a443-c395588dd330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0862e49-ec6d-4172-b27b-d6d9514f8038</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35157172-bda6-4088-925d-31e417c49a9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2262ff17-7b6d-4d0d-9280-ebfc283ad6c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17bc95e-e344-44ca-98a5-431a9c95ef2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f72e35b-8240-4a28-82cc-83b5616416ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e881e84a-1171-4dfb-a2be-b3cbe44e207b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aba078ac-e39f-4ab0-999e-0e3af442c48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a90363c-b163-4569-9e50-8befd7828b55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79d8a00f-9595-464f-bbfb-3c0d0813500a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6d31b6-ca62-440c-8c01-17b1a7a163dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7120954e-3c36-4e62-8d74-07ef80290308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc268fb-a202-4a05-b3ae-9727ea8b5495</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00546fed-c2d5-43c1-9335-2af0ea4097ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cad55ca-2f1e-49bf-8d82-de05bdd40c8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d47a29-6925-473f-ad83-c3b2f2123ced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e646502f-355d-4786-bc05-347e5cabbd82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fe465af-5d57-4ddd-ac9a-8dd6df3cfe52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6612ae93-370e-45aa-ad66-9b31aa7a2c14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6f6e6a-1a53-4900-a668-7ccfd68d2f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1718098f-0366-442f-9eef-09e48f935012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>519fcae1-16f6-4eec-9143-877efc48d3b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9415cae1-378e-4d63-bd0b-e28305aafbdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ae29c3-04a7-4b7e-aa95-5ab5135a3ac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e147433b-18ec-45d9-a7ef-b92e9d6927e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b240dbda-eee9-4ad5-bb4a-59cdbd5f1cf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25f66fd-199b-4c68-8ff4-f34ca03e65c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24cb16bf-0b31-4374-a43d-49b1d9c17ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ada59a-974a-4831-9768-ef04cae87ae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9420fc4-8597-44d8-a15e-4727ee384f9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ec606cb5-a26a-4524-8dfc-4f879021446c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493784fb-7fb4-45a6-87e7-f4f146df701e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa068b2-89c3-4816-8570-02d7120391c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126fc9aa-b5da-4345-b9ef-882d9d969d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23e08bbc-8ebe-453b-bdb3-361f7caca056</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5576e6de-a542-41ad-a0ce-f8788bf3ea56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8905e195-dc3c-4552-a40b-e7c28d13630a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742a647d-cbcf-4069-850a-b269850c5e93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f444c251-f60c-4878-bcb7-4fae54400368</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>673acf39-7a3c-4707-a7ed-45a52f044e00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a68dcd4-a562-437c-bccc-bf9bc8e0af8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e8acb43-afb3-4166-86c6-e98740716ecd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4321597-f1d1-4f30-9cfb-db3e3b395686</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87cf070-0b7c-4b6f-9c27-763e4f3e4469</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3d7c78-aea1-4cde-ba50-61f710bd48d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76988200-8c11-460d-9507-5156f68500d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a41de8d-ea45-4421-83b3-e014299e32c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b84b12-348e-4c91-b952-bde70369ab26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fc7c075-88df-4375-bc0f-1bffc1c83903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3636f4d6-8fab-4971-a60a-3c4713f44cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03a421cf-2565-46fc-9e4d-29634f5c59d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>869d125a-f239-48cd-bd9e-023bc42a5f63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065ba68-ceb8-4bd1-a07e-0683620aa334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14482272-64bd-4d91-ae2e-f2e56be371dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>347701ff-c12a-4d7f-8b6a-7fcac63149b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f43fb9dc-429d-468e-8167-4427051bc699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>438bf64c-adfe-4535-a597-753e36a56579</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3f3c319-8945-4ce3-9c39-03e8e01770c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2775c06c-1dd9-4eaf-8127-18dc4ec6ae75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88a34bef-f306-4ea4-8685-05a1db211f77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d6d0df9-217a-4611-a920-ef9f798e6ea4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd29075d-124c-4338-a6a4-16d53d41c775</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a330d2ff-ee44-4517-86c0-9d1a9091269c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0eed897-821e-4c07-bc5d-76e89c2cae1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03adf14-b08f-4b23-9fb3-49876b01bf88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a7cd912-62d0-4dcd-b564-752629819e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>486be436-e495-41e9-950a-99fcac432542</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ecadd1f-f5d0-40ed-8f11-fb6abba4def0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42fec78-f441-409a-91b8-9dbae0e256f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a00edef-e76a-4f79-afd6-6ed9a15a6993</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9008d31-8d4e-489b-b5ee-857388cc193e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f356ae7c-22ef-42ce-9a45-8794a53dd323</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca98150b-93de-4a5f-87e9-b6dc43c503b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b3b3ee3-0e6a-4791-b810-81957b094c27</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0a097ac-6fb3-454e-bc04-3d99fe62950a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa1d4120-e443-406b-b1f6-b0ee5b9acda8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fbefe8c-f413-479d-85cb-8d54f2d6af71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e829f733-1c56-435a-8f96-b9aa5e974b76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dec2d983-d5bb-47bc-bbd3-87928bbf6ee9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1e16acc-fb20-4793-9ad3-5929ffbcae3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a688a92-b189-43d1-9c3d-9467942b6737</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6343f7d0-40fc-4704-90fc-6ce29440c243</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d02c8f4e-4a78-4ab0-ab9e-38e8d649c4a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc2839a4-d297-42f0-8e51-d054bb3834ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3147bc9-e4ef-4865-9712-c0a3767c990b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b82766b3-08a2-48cf-8bbf-36bb4d193854</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4818957-3d47-4366-bb5c-49ab45ef61bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d3f646-c132-4a4f-bde4-7f74aca31867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcfd2cd-895a-4a15-9ed4-e0b4d826675d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b577b4-5ac7-4784-a54e-8f0a0fbf03e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a5b2ca4-7cba-4eac-bc2f-22dceef63508</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4958e61a-454e-4dcd-be93-df1f5994af2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8f5237-04d8-42b7-8a28-3dc64d8037bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba4fb387-74e5-41eb-b235-e12b2285c116</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdb05df1-9cdb-4a16-a68e-b4e91f5dd83a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c82a92c-3bee-4a3c-88c6-45c5c13d463d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83eb501b-01aa-466c-a842-09ce27cad1cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1989de11-c2d5-445b-860b-a56c5925a480</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>befab2ab-4a17-4fb8-9f49-dcec86022e6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f518ba5b-3211-4080-bddd-df1ae3b63515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>949d3ea3-353c-4720-a570-892c6472b886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd28be8c-af76-4569-b3e5-e2464ec067f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fef510d6-7885-4868-be89-79d9c51a9aa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a302aa9a-c04d-494c-b630-83d0e834ea07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cf0cd74-c2d3-4255-ab14-fb42b998f1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f1d418-5c5c-49b4-82ff-7f1478373e4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00d9af8c-a4a6-46f7-a7c7-f2ef827a7ab6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50341392-cdb7-4c95-9af7-0c4a81cba203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a553b4-20b2-4baf-a304-edb8a8e20d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cd4c36-96f9-4cf1-98f4-7d4777ab2e0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c0870f2-c759-4999-94a4-4e7b8c776396</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8177568-b896-4449-8672-30f3f1f63136</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce5c775-75d9-4113-9e96-ef7b44656e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d36444-0632-4ee7-8944-e721b01f2725</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2ce074c-9021-4eb0-b27a-13319512126f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0473ca4-5853-4b8d-b6ed-89bd94e98911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c906fb4-8fea-49f4-8fe8-14c647909e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e4c15dc-870d-409e-9e61-70efeee10ba7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
