<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Interbank Test suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ee623f7e-ebaa-4018-8e48-d2a8d9124436</testSuiteGuid>
   <testCaseLink>
      <guid>f6c35696-8608-4b26-9d9c-5b3b8e976a8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_NonAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd28f3ad-e669-4f64-968b-32375a829b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111cc5b6-35e9-4ee9-a67a-b822cdfdb437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>407d8473-e8b0-401d-b152-ecd818900b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60a2ccb8-b994-473c-acd5-69bbc50c4e08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Interbank/Interbancarios ACH - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3907ab7-d505-4ec8-9a17-74cde1a499bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4db195c-00cd-44b2-8e9f-86bb94514a6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a63d5d3b-156f-49cb-a376-afd23a232a86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>102b301b-8944-4453-9c21-ee964122662f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2f5864-3c43-45cf-955e-0e7579616685</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77cf893d-2b08-4b5c-87d2-bf379d4ccffd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13efb0ee-0089-4f6d-836b-6a028a33ec4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41e39917-dfe9-42f9-9fff-e4555dc263b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20240e84-10e8-4fe2-9ff6-78c256cedc4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Interbank/Interbancarios ACH - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54b04fc5-7a22-45c0-a690-35ab6055af36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd52824-049b-41af-a580-ce598a0198d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c91da2-49f4-4770-b750-ad27f40dd30d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c42e0a5d-87ef-4072-a238-77a83ba95078</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>035a40ec-46fe-4caa-aefd-e92c7bd357e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>414141d2-c5ea-47b0-8318-565c4dba1e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94417971-ef0f-45cc-b9c5-da54f8834da0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86b792f6-bdf6-43a7-812e-1b44ee5d7da6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5eafc61b-c07d-4a11-8f04-d186120741c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Interbank/Interbancarios LBTR - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6be0c37c-398f-4d46-83d1-b6f649548d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64f5cf6e-09a9-4d0a-9732-c39e49c7e5c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f413f677-2696-4669-9915-37d4450e93c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e31c59-f87e-49c2-b5cf-a6a3ecc653f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50cbdb11-aaba-4a7c-8f00-f70e2f4eb668</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c032f7b0-915c-4170-8dad-8fbf23aac9dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2de488e-cec7-467c-9a62-0c949d1d3b54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edd2190b-3d32-479e-a61d-dbd6670cc3d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89039d9a-66da-4a7c-a11c-1a263170ab8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Interbank/Interbancarios LBTR - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40498e7d-88f9-41ee-9b3c-69506498550a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f518f96-5622-4bf7-a573-a435cf988a64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acdf97f-8a9e-475a-8109-9133f51d7aba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44387a5b-931f-4817-b998-cc79cc13b291</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c058a1-aa3b-45d2-aa18-8a1352273509</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81049121-0d50-49a0-a496-a8b5314e57c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbc3188-be1d-4aa1-bd66-d195491e2267</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efd50974-2912-4b28-a6f5-d57f9ef4404b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
