<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Selected Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7bea6cef-0551-4169-b6e3-96366c302689</testSuiteGuid>
   <testCaseLink>
      <guid>0f3e1cd4-9cef-40fb-b951-8db17f687deb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>132b2780-d7c9-4647-ba5c-6b56232f9387</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultaCuentasAhorro</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f97b4f-bcc2-4488-9769-a754fa7cfbbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05ac7e6a-ccdf-49fa-95b2-93d41982877f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450e59a7-8847-4b3c-9f87-bc6a8a515bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>610bb91e-4626-407f-9d66-bd3d9910251d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b0058a3-5a87-4f67-840c-538f62119987</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3188f450-d884-4f19-a12b-282ca5455a71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>727d38a7-3e67-4ce3-b0c5-261fb4658e06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aef74368-5966-4fff-8ec5-26a2f002f25d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultaCuentasCorrientes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f878f7-b7b0-4b1d-bee1-376e978cec7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cabd247-1e32-4149-bd79-6e48f699dcb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c0b7ac8-a0cb-41b4-b139-98b3dfe7ba30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd255d3-743f-48ef-9205-c735e3559031</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46b710b0-45f9-46ae-b1b4-1261ce1e147e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89a7c297-718f-4858-a203-813ff1910a77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e0d0b4-9788-4f13-862d-82868710b24a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08f239a7-62f7-47e1-9f23-78eada775994</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultaPrestamos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20bb00d5-7788-4703-b935-58213dd9968c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e47cc6d-198f-4923-a2bb-89705d4ae9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2e7503-4d2f-4434-9171-3edb503848dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f8cb7aa-cb7a-43dd-9302-adeaf6e1a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9423200-5beb-42e9-9dad-280bf020147f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88b7696a-1f55-423a-8111-b3bfadfe2910</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultaTarjetasCreditoLocal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a071fc80-a945-4536-9c37-b29b623443e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a09a03e-6d3a-4c0b-9331-7f6093952026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd53f24e-96dd-462f-b3f8-0547cb0d514d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54e57efd-9196-4285-a66d-94c00a718ba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e1ce9fe-768e-4423-9bf4-eefbc66e0a0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>032ffcb7-65a7-445d-9bf1-1a066f11d711</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultaTarjetasCreditoFDR</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d340f18c-5243-46c9-ac80-b55365736010</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90cb10d2-f16a-43e9-a154-ef7cdce7c31d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1859eb39-ce97-4b58-a5f3-7c172d9101e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1735052d-6fe1-4b83-9620-daec321fab5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fd2e47b-1f85-48ad-809b-3368f6f501ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>012dc0dc-046c-48d0-a696-d137496980a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_ConsultasCertificados</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a522fe4e-cfdf-4621-9a76-1efd674f94fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>785513ef-bb01-4ee0-b2c2-db50866f6d77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e396e25-ca88-4561-b310-612e8ccba7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb1feb99-a2c0-41d0-87f8-18d9a7cdf8e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a7b3fce-fc01-4f7a-a82f-aa515a032d5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7d61beb-6d2d-4cee-915f-664a12c9e6a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_Permisos sobre cuentas (Dashboard)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c611ef02-6b9b-4309-b556-1424cf818df0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b8f8a70-df97-4f62-8342-555c31784506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf0bb47-efaf-49be-969a-835c677e62be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483de135-bbb5-4db4-aa81-f3ea50bfee22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>078fb06f-2d7b-42ef-bb3b-e49c7be93f5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Estatus de transacciones/APPEMP_Estatus de transacciones - Consulta de transacciones aprobadas por mi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d58f2b1-7e42-4d03-bee3-62e9fa283a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65598a8-cebc-4c62-8e29-9e1d15cf3f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e3eabe-7cec-4daf-b26c-b62db914717b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ace1cd71-6c75-4f3e-bdb5-312c2cccc737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_De-register User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2cad8218-d3c2-49d8-92ec-9a7a700d0c55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_NonAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd28f3ad-e669-4f64-968b-32375a829b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111cc5b6-35e9-4ee9-a67a-b822cdfdb437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>407d8473-e8b0-401d-b152-ecd818900b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36c8aea7-d9aa-4422-bf02-d264f2b2461e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Impuestos/Pago de Impuestos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e98643-da83-4592-97c9-2216f2387bf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74c7813-0ee3-428b-988d-a264f7c8b3dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfe6384-b6d8-419a-90ad-96756f318188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe8c8f73-c6ea-4917-ae38-8a05668c71c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb0deada-0c78-49b8-a35e-9383e931d81e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31e5844c-57a2-4ee2-8efd-8d3972c67972</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4225e14f-5820-48a2-8d0d-dad00a0151f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b905cc24-6d44-46af-860c-f74039a51ce1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecca641c-3766-4d78-8e6a-ee7336c60c8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412975a3-2cdd-4d6d-90a8-b17855ccd425</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fa7c8f-4088-490e-bc9b-cbf61d4cc80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebf69fa-ad46-4e15-a4c8-75159d9383c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70152408-9410-4e76-a045-1fcdbb4f644a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00364c08-e9aa-4565-85d6-c1a4036d0fcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa54a79f-f10c-41ba-983f-2cd0570c97f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8869695f-6193-475f-a052-45d198dc1b13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1af4b62-5e53-4f6d-9d8f-03a07c0d56b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6eb3521-87a2-4ef6-bcff-661af7b60b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24fb81c4-f330-46ec-b74a-9bb30ab4c4a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d46f146-2f3b-4bc6-ae22-3ea55e3517e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51aa1545-3196-4f45-a740-a30735b2e654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20b136e-f062-4a20-b028-a62b4c78b315</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b653a8a3-d029-4a50-ab64-64ba62fa2106</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba053f78-3441-4b72-8a4c-e69794d5129d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Entre Cuentas/Same Curreny/Entre mis cuentas - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0879bc44-47cf-4a0b-bb63-7674718a3837</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b1835c8-2ff5-4cbd-be16-8c1e00754bbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f61c80d-4084-4e19-a88d-3035032c1a34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440b0a3b-1275-4c81-9399-89481c8fac89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f45bcfd-73b7-46d0-809d-2d655dcf55bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2abccb15-a82e-4d6c-8764-6f017022bf40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b64ee060-4809-4f23-a0be-fc250e9a66ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c0cca8-a3a7-4a36-962b-930f9412030a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3874002-8da9-454f-b4e9-ae63151a7889</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffddf819-da0e-4827-8798-38183a6a5e49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Interbank/Interbancarios ACH - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54b04fc5-7a22-45c0-a690-35ab6055af36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd52824-049b-41af-a580-ce598a0198d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c91da2-49f4-4770-b750-ad27f40dd30d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c42e0a5d-87ef-4072-a238-77a83ba95078</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>035a40ec-46fe-4caa-aefd-e92c7bd357e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>414141d2-c5ea-47b0-8318-565c4dba1e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94417971-ef0f-45cc-b9c5-da54f8834da0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86b792f6-bdf6-43a7-812e-1b44ee5d7da6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80f6ea88-4e98-4f51-aa91-6b87460d8cae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transferencias/non admin/Tercero/Same Currency/Cuentas de terceros - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e63103-25a9-448b-b954-b87bbd50d4c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5998523-80c7-4cc4-8552-77cc3f67e0ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24cc32c-8a6a-46c6-a982-1e837445ff92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6f44c95-d6db-48cd-b79c-fd39dc4037ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4877f2-970c-4917-ba91-4bab7fab14e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd68f12-925e-472f-b700-9d01ae0663a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98201318-12b2-4d84-918e-96e93abdfad6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a8d4b40-b621-49a1-bf9e-403ef06e40b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b70b388e-608f-455a-bd5e-02245870b2ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Desembolsos/non admin/Desembolsos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d8299b1-cd94-406d-8f69-d533d9f9b178</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dd60788-ee55-4e4e-acac-8a319ec96075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>217c95d8-6042-44c0-9469-235b6ac17c07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c05076c-b62f-4416-be60-d29d24b22f96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>523062eb-c88d-436b-92e4-c67d52c79afa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba496063-a652-4913-91f4-3112faba2332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c9327a5-9d8b-43fc-ba55-618456642a27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35846af2-28e8-4b9b-bf3a-12275fdd4b9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57e061fb-0543-48ba-8360-c4351fb0537d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_De-register User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>61ac5267-fd5c-47f1-97f4-d4246f3e747a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa18840e-6437-41cd-9e05-c15082c693d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f52e6bd7-9e64-448f-88fe-a60340f0e307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68f625f-0dc8-4266-945d-c507a36b985b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d195309c-9de5-4df4-8e72-a33a4108fe05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0024c20c-f867-4b27-867e-cc6e7e3ea974</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dd448f3-7f5e-4978-b1c3-3f59f7bd2014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe6907e-8a53-402f-9443-aaa6311844d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abe4f6b-8ba0-4ff2-8b04-e1c331437074</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c992a820-62ec-49d1-8980-79aa328545a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493784fb-7fb4-45a6-87e7-f4f146df701e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa068b2-89c3-4816-8570-02d7120391c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126fc9aa-b5da-4345-b9ef-882d9d969d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c90d2ebf-83e1-4d7c-942d-d05c8fe29914</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0473ca4-5853-4b8d-b6ed-89bd94e98911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c906fb4-8fea-49f4-8fe8-14c647909e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e4c15dc-870d-409e-9e61-70efeee10ba7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6b77777-ceab-4938-aeba-bf12aa722e35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25f66fd-199b-4c68-8ff4-f34ca03e65c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24cb16bf-0b31-4374-a43d-49b1d9c17ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ada59a-974a-4831-9768-ef04cae87ae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91011dfb-da32-4805-b20e-d385fb62025c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
