<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ts_Aprobaciones y rechazos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a15c082a-6d4c-4635-b8e7-3839e8815aea</testSuiteGuid>
   <testCaseLink>
      <guid>c1589942-be18-4caa-a52e-79d2d697344a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ca64d66-5a3c-46c2-9e76-9fa3fc6ddd28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6944eb-5c0b-4fd4-b5cb-be18fba7ffef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e117557-129d-4dd7-9f68-ec25a105b521</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9846dda6-f143-4795-ae5e-43d15b523b6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc8d486-32a5-41f6-9f5a-a08e411d93ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c30ed68f-c04d-4551-ac7f-dd06b898d011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85559751-e90a-4aec-b8e6-fe119ea16571</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e016ad-fd6d-4800-b47e-ea39f590f8b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15f87dde-ba8e-4a3d-8897-2234f45c0f4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823fd51e-e6d3-4816-972e-43e3ee8bb59d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6009164-ecb6-45de-80a5-efb8ea20fae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81dd6383-a970-471d-b578-0b95ac1b9275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43a8dba3-b417-4490-8cd6-5a7e66572afb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf8b6449-12a5-4494-aa3b-8031ca7074b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc6bca0-c3ad-4c30-912b-c2f62ed1e8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fb63c8f-41e4-40ec-b85c-bbf4f9bbb158</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17d93bb9-e804-462f-9456-c02aa4054f16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f52e6bd7-9e64-448f-88fe-a60340f0e307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68f625f-0dc8-4266-945d-c507a36b985b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d195309c-9de5-4df4-8e72-a33a4108fe05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69797662-e82f-4157-a811-8e7dc00ead33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d282e9b9-5b65-4a42-a645-8c05773c0a66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8c2a513-ba18-489a-8666-5abc6f77fe31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>527cc230-ceb0-4738-bc02-360923063430</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21d5280b-48a3-4fcf-b3ac-295167a8e2ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288c30f9-eeea-4842-a351-ea5297897586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d45a9a-fd4c-4502-9294-205852b29214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0530d7-48fc-49e9-bc04-fdc392c245d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf126572-8bc8-40d3-a3e4-44802df230ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eed3987-39a3-4bbc-9321-323c417e3bfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f7d6a47-983a-4ab4-9405-874fc59c0fd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c1b5ce-44a1-48a9-b53e-80fff18211fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c34c3b75-9c4b-4eea-9a4b-64b7647a5954</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d58f2b1-7e42-4d03-bee3-62e9fa283a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65598a8-cebc-4c62-8e29-9e1d15cf3f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e3eabe-7cec-4daf-b26c-b62db914717b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8790097e-2f1e-4b6e-803b-20bcdc237172</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dd448f3-7f5e-4978-b1c3-3f59f7bd2014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe6907e-8a53-402f-9443-aaa6311844d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abe4f6b-8ba0-4ff2-8b04-e1c331437074</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0f88b69-4694-4957-a7d6-3207f6d13077</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>898260f7-d217-4256-8c4c-f26df7b609e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b19755c-ad99-4c4e-8b9a-d52e1b0c017c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f1ac89c-96a0-4d9a-ba68-7c584050edc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f4d4116-1c6c-407b-9cbc-821f8263d271</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8924610-c7e7-43ea-8dab-4e45ed64c520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cfa752-2977-47eb-b943-1fe547aa25ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452f5c07-7e6d-4a63-9cfa-5860c53a6db9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9f152ed-4ad4-4ef7-9fcb-496c456db9c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35157172-bda6-4088-925d-31e417c49a9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2262ff17-7b6d-4d0d-9280-ebfc283ad6c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17bc95e-e344-44ca-98a5-431a9c95ef2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb58d35f-d649-44b4-811a-d1c151e67993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e881e84a-1171-4dfb-a2be-b3cbe44e207b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aba078ac-e39f-4ab0-999e-0e3af442c48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a90363c-b163-4569-9e50-8befd7828b55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76314538-3a7b-4950-a530-d29e3e4cd42f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6d31b6-ca62-440c-8c01-17b1a7a163dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7120954e-3c36-4e62-8d74-07ef80290308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc268fb-a202-4a05-b3ae-9727ea8b5495</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d955635e-2943-4f02-9374-6c4e3f6fdada</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cad55ca-2f1e-49bf-8d82-de05bdd40c8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d47a29-6925-473f-ad83-c3b2f2123ced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e646502f-355d-4786-bc05-347e5cabbd82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c8d0d72-9402-4699-bd76-d7ec37c937ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6612ae93-370e-45aa-ad66-9b31aa7a2c14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6f6e6a-1a53-4900-a668-7ccfd68d2f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1718098f-0366-442f-9eef-09e48f935012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78394a72-d7c4-4bcf-8f06-12fe40770eac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9415cae1-378e-4d63-bd0b-e28305aafbdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ae29c3-04a7-4b7e-aa95-5ab5135a3ac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e147433b-18ec-45d9-a7ef-b92e9d6927e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f220589-e0a0-4835-b9e4-20ca5489979c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493784fb-7fb4-45a6-87e7-f4f146df701e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa068b2-89c3-4816-8570-02d7120391c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126fc9aa-b5da-4345-b9ef-882d9d969d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ef0a4a6-7d86-4759-aaef-1fd48e9511b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5576e6de-a542-41ad-a0ce-f8788bf3ea56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8905e195-dc3c-4552-a40b-e7c28d13630a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742a647d-cbcf-4069-850a-b269850c5e93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7a21d32-fd60-4e06-83d0-e21f5aecba84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d3f646-c132-4a4f-bde4-7f74aca31867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcfd2cd-895a-4a15-9ed4-e0b4d826675d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b577b4-5ac7-4784-a54e-8f0a0fbf03e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc12751c-3298-430f-977b-f5cde26ae2cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4958e61a-454e-4dcd-be93-df1f5994af2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8f5237-04d8-42b7-8a28-3dc64d8037bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba4fb387-74e5-41eb-b235-e12b2285c116</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16908ba7-c1ea-498d-9243-87e05cf599a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c82a92c-3bee-4a3c-88c6-45c5c13d463d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83eb501b-01aa-466c-a842-09ce27cad1cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1989de11-c2d5-445b-860b-a56c5925a480</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fd8f231-819d-4a3c-83c6-61150333398d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f518ba5b-3211-4080-bddd-df1ae3b63515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>949d3ea3-353c-4720-a570-892c6472b886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd28be8c-af76-4569-b3e5-e2464ec067f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e52e719-d07a-4997-9140-d04cd980c7d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a302aa9a-c04d-494c-b630-83d0e834ea07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cf0cd74-c2d3-4255-ab14-fb42b998f1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f1d418-5c5c-49b4-82ff-7f1478373e4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fef3c2ff-99fe-453b-bd3b-b9f2ecbbfe2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50341392-cdb7-4c95-9af7-0c4a81cba203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a553b4-20b2-4baf-a304-edb8a8e20d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cd4c36-96f9-4cf1-98f4-7d4777ab2e0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88b303ba-a55d-412d-bdf7-a4feda0c6899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8177568-b896-4449-8672-30f3f1f63136</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce5c775-75d9-4113-9e96-ef7b44656e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d36444-0632-4ee7-8944-e721b01f2725</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7611893c-1244-44e0-933b-0ee3ade63d0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cheque Deposit/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0473ca4-5853-4b8d-b6ed-89bd94e98911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c906fb4-8fea-49f4-8fe8-14c647909e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e4c15dc-870d-409e-9e61-70efeee10ba7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9031141d-76dc-4f4f-afa5-df38cf864d1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7e0fd1-56d1-463d-a138-febf1a7185d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eddb0eb-2f3a-4cce-8bbf-4eb94cedde2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bb15204-41c0-4e14-98e0-ceae28e76bc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94f881de-a507-4cad-83ae-4fe2a89d1739</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b95ce6d2-0152-4f00-a9e2-f88304082c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05830ecd-35df-4bce-b10e-92a352999129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee991d7d-3c4a-4016-9790-7178a2f8617d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9e2636a-42f9-41e6-b686-f23617152dbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371bf4eb-4d60-4939-b2b3-05777f01dd57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47db51cc-a80e-4435-8327-7b49fbd1f6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40f3653-a31e-467b-8d35-a1172195192a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd30330-9613-4d9a-be3c-a0e1658ce876</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b6017c-b6c5-4af3-bd0a-8fe4c3644a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ed6feb-72d3-435e-b2b0-19d299aa7ded</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd796fb7-7c7f-434d-bf1e-ae7307642b31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ab0d8b2-ee51-43eb-8890-4ed8e8921d34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5f80293-3ea5-4fcc-afc0-45bff68df807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d6fea8b-1e9f-4500-8a54-b78ab60c2cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7db8be4-75b7-44a6-99e5-3f112fcfa10f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae59effb-5a6f-4aed-962c-fa54ad893518</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20dfcbe-cd47-40ad-92e5-0c2355497ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d16fba9-74c5-454f-8f9c-4ff0977b3480</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a8f42d-3aa2-4d36-88aa-6383e828bf1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fea4054b-9380-45e9-b96e-7a58bf4b9998</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a966c47-82f5-4c63-98e0-6dd56c0784c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6005fd0d-295a-4f11-8653-f7414f308143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84d725f-dbc2-480d-a705-8d57c46cbc64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f81d53d-a1bc-4457-8ed0-d361d117f412</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b29267-35fe-4a53-91f9-46f5b5b55121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d88669d-ee6d-4ba0-b2d5-97b841e64a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a6d77ea-70a7-4b00-9e46-ac874a7f1ebc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7192aa12-b9b6-437f-806a-85938e7290a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>673acf39-7a3c-4707-a7ed-45a52f044e00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a68dcd4-a562-437c-bccc-bf9bc8e0af8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e8acb43-afb3-4166-86c6-e98740716ecd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5751aa1b-e4cb-4a93-bcdb-e0f1492a1240</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87cf070-0b7c-4b6f-9c27-763e4f3e4469</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3d7c78-aea1-4cde-ba50-61f710bd48d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76988200-8c11-460d-9507-5156f68500d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0717f1-a71e-4794-b4d7-6eb4d3a3b4f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b84b12-348e-4c91-b952-bde70369ab26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fc7c075-88df-4375-bc0f-1bffc1c83903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3636f4d6-8fab-4971-a60a-3c4713f44cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>401899f5-0e9e-47b7-9c54-35bda0fc2ce6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>869d125a-f239-48cd-bd9e-023bc42a5f63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065ba68-ceb8-4bd1-a07e-0683620aa334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14482272-64bd-4d91-ae2e-f2e56be371dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78576cb0-95c0-4ec2-9aa9-055789be944e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0caa56-d3d9-4c54-8f55-a46480f1de9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a076830-6686-4f5b-9897-dd2ea5995c82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b12bf6-4913-4410-bb83-df04c70ea1f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ff76440-d3e9-4a3f-8d8f-e61145ef2932</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0bf3b9-f003-4a8b-a70d-07b11f7c82a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6460655-5d78-4924-857e-82dd39ac838f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc05dc2-a5bf-4a46-acc5-74a88fe5f330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0da428e4-fbb8-4794-a7bf-e69a2d189e98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a946c47-78cf-4cd7-903f-a573cb44b48b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c86eb9c-d08e-45aa-86ac-0eedcca0c52a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e069694f-6e5d-4eb8-ae86-5ad1ec73495e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e6e96a2-722b-429b-8e76-353457e26329</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a9a1cb1-8e23-483b-93c6-ea9a62c05b2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e042d2a-6346-4d7a-bd97-a0976fb35887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1140dfbe-a837-4495-ad63-eddefad6ab30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76f0d103-998d-45b3-936b-8cada556a337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcecb421-3276-48be-a4af-daad57d378e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc7987b-7cc1-483e-aca4-4c34fa7d7361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4479eb9-8831-4187-958a-5ff035d286b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae8d0d25-4273-4130-8aff-7b581f16a2f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cfefeb9-2433-40c3-a5f8-66aa1bae33d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b53bb318-e940-4303-aff5-563aca6ea0dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00315e63-a93e-462c-9752-a2d41a2357d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63f944c1-af16-4218-95d9-a095dbe519ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d4e955b-18d2-479e-b335-b7845c82bc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01789308-15da-46d4-be8c-65a8cd299012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d782590-a3b0-45c3-ab46-70e3ec76214c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4f01b9a-6d1c-4618-a40a-f3e345310f32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ff0a41-aa52-472a-9a1e-76f0bfe4c4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce280073-7969-4923-9ea9-8f67506bad5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab928e9e-cd3b-4421-a6a1-200aa186244b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8371aeb1-b721-46b3-b1d0-0a8783ea4a73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f443579-c940-4978-b5d6-b68cf64b685c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1026e239-b837-4602-aefa-d1637be13bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf28faf9-2a1c-43b2-8f1d-465f97d1811a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c02c99b7-0414-44a1-b9a2-1c95dc8420c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4845520a-fcdb-44a5-b708-38c0a03fe593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e9c875-d714-42e7-a25c-c3ad09ba8c18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82daf827-6ca5-4672-8c0f-f6d7161e357c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbd0f934-1b77-4b3c-891b-c3a262751264</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da60edf-3c67-4ac7-a639-9e818158179b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ef94b9a-e406-44da-be0e-7a994847b3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ccaba82-30ac-4008-84ff-b69655780237</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f4c270c-8f35-4044-92df-659b6b1edf2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f55b1b7-3ff2-4a9b-9cf4-4a14f5a795b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cf57cb-0b67-493d-abc3-e42a054783a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dbfa71e-f05a-456a-ace4-eb20fa35b80e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aca33c58-2fde-469c-9092-57c3f6cdc122</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from burger menu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29539a93-417d-47bf-b0e9-10b6c0f63ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a15d660-8462-40da-a55c-490e76a91edf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e785d9-a2a0-4d77-946c-e3d99bc35ac3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23c99d7d-da9d-491a-a23f-b60933817ff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from Dashboard bottom button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daa645d1-c041-4700-bc63-c33c951feed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e2c8af-8cfd-4fbb-add6-f205bb553b51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfea876-c7d0-41ec-ae8e-28610080766f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>daf539b2-5d51-4994-83cf-eb81b7cea0fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25f66fd-199b-4c68-8ff4-f34ca03e65c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24cb16bf-0b31-4374-a43d-49b1d9c17ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ada59a-974a-4831-9768-ef04cae87ae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51b9db45-abaa-45af-94fe-89b32144399b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
