<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ts_Estatus de transacciones</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9d89f430-8193-45e7-8002-1ac1dbc8209f</testSuiteGuid>
   <testCaseLink>
      <guid>cd814af3-4f35-47c6-a5a0-7891cbe1ba6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61e38ab3-8079-4556-9de1-bdf8dad3e8d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Estatus de transacciones/APPEMP_Estatus de transacciones - Consulta de transacciones aprobadas por mi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d58f2b1-7e42-4d03-bee3-62e9fa283a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65598a8-cebc-4c62-8e29-9e1d15cf3f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e3eabe-7cec-4daf-b26c-b62db914717b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>485a3e35-61a6-4734-afb5-37bc8226d71b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Estatus de transacciones/APPEMP_Estatus de transacciones - Consulta de transacciones completadas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6048ddb-4162-472f-932e-38947b949f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54333551-f95b-4cb3-9351-e987992d246e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05a8f092-b42d-41bd-8cb5-ce1daec37ace</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>902fe705-accb-4572-ac4b-b3cd57042efd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Estatus de transacciones/APPEMP_Estatus de transacciones - Consulta de transacciones rechazadas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d25658-aa8a-4408-908e-ac27a7d594f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b28d52d5-5b6a-4bbf-a3a6-17e2b58a79c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab5e3369-c729-4e4f-a2a0-6efb7aa4a152</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
