<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Login All Test Case</description>
   <name>ts_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9ab3f6d7-3888-4216-bb37-c075f3534390</testSuiteGuid>
   <testCaseLink>
      <guid>1a9329b5-6e4a-432b-bfd0-518e60a87a18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_NonAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd28f3ad-e669-4f64-968b-32375a829b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111cc5b6-35e9-4ee9-a67a-b822cdfdb437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>407d8473-e8b0-401d-b152-ecd818900b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9e6efa1-c060-4280-8cd4-da480ac0f451</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Login_AccesoGeneral</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d682c10-f977-4294-ac3f-fd7aba1c0567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f7bd8b-9f16-4ce6-b65a-9174caf0e2e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fec017f4-6761-4d46-98c8-2ac3808deaf0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>433ee584-09dd-465f-90fc-44d2b8820ff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login/APPEMP_De-register User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>39f77634-7590-487f-a789-05e7eb55be96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3b78623-d59f-46e9-ac46-b8560bf8b0ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Consultas/APPEMP_Permisos sobre cuentas (Dashboard)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c611ef02-6b9b-4309-b556-1424cf818df0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b8f8a70-df97-4f62-8342-555c31784506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf0bb47-efaf-49be-969a-835c677e62be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483de135-bbb5-4db4-aa81-f3ea50bfee22</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
