<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ts_Pagos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fd9b64e3-6f7f-4837-9e28-7498862b6ab5</testSuiteGuid>
   <testCaseLink>
      <guid>a70778e9-4165-4b52-a835-39f9816f66f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a9285af-64d9-4f2a-a120-e44efff74859</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Impuestos/Pago de Impuestos - Submit transaction without approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a23dba3-81f4-4ca5-983e-b90ed39ddfe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb62c4a6-41d3-48f5-85d7-9643ea23ad33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c32939-639b-4880-8236-8efeffd177ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e08c5345-89c8-497d-955f-e854aac078bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b304a69-e208-442d-943c-f1cbc3b897e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>897e354e-bebd-4457-8210-0f825644a0c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction without approval (From Dashboard Prestamo)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19385ac3-cd2f-4abd-9634-87ca457c64e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a78fc8b-6323-4fc2-a5bd-0005611abd0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>915c055b-dfa0-4fdb-beaf-8c0997432c23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0299f224-f964-4e37-8d0e-f324a31b7c8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa88999-40da-416f-9f3b-ebe8d5045312</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba8b2f3-a3c6-404e-84e3-5eac4a8515e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e4fb87e-bcba-40bd-9c71-13b758848174</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54702f73-ab67-44f4-b449-2504b345c1b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b8a1cde-1d63-4b24-a6ae-899c14820106</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction without approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dd7fb2d-e21c-4fac-87ae-3ee34b4bc32b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f708c167-d7bf-4b37-8cbd-95c362d284a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48bf36c9-fc2d-49af-af22-54969e2bc107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>911301b1-ff1a-499e-8dda-df4e555de2c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ebc47c-a172-47f0-b058-6a0009beea4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5777ec77-5ec4-4ba0-a5b3-8d40d802b580</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59dae1d3-7426-4f6a-8a96-bc38a22ad3f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe00c8c-cb98-4efe-b81a-d7278f9e93fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11fdcb5c-d49c-4b04-8888-079560465b83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction without approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b75d1de-d157-4863-b040-374be9543d3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efb728c9-5827-4a37-bd96-a46b062a2536</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b6f1cc-0b0a-477d-a6f1-00508539573c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66efbb96-29f8-4445-9af0-e46c8b6806a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e978805-081c-4e41-b899-b95e52166362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7c74d2-0f2e-4fd2-94a7-ba5145776d6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdf96d6b-c5ac-4a69-a262-511b0d570e7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a32e860-6fd3-4778-ae8d-81e504bba5ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6880b17-fb80-4bca-bc34-46ca00ae2b36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction without approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddf65c03-5179-417e-a49a-2e8fa7ac53b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae0e18cf-fc20-495d-866a-4f388c2ee8ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0940be2-b5f9-4700-aad4-3a09b54b1a36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40904d0d-5add-4a93-8e95-4d34236c5f5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e67a052-d39e-4e5f-a7f5-09d921315f1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7bdbdd-e77c-42d1-adfe-6955dbe12ed5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>defd3b59-68f2-4691-9564-ceec98f4ab56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8de21ac1-771c-47d8-b2e0-e13eea3c35c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68813176-1bb3-4b8e-b528-08fe18d44f37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction without approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f59594-ce51-42ca-a291-c89c341b8baa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0127ad7-5771-4e97-b894-15e89a5e0369</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3136f2f1-c80b-413c-8d67-0ab13be5a1c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ba53cf9-9512-43fb-a168-54f0e0c65703</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>804ead90-7827-4e7c-a943-4c55f552cfad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbb5989e-9c85-4a38-b1e1-1dff48ded631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d40abd45-360b-4cdd-ae3c-aa5074c22d39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d02f20f0-8f59-4f4a-8e55-e6c201c68a6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82997692-bab8-483a-b27a-ec91a7430c64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction without approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3d69277-12c1-412b-ae0b-c1e389944850</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bca6d1b-fc4c-4b0a-914c-f97df112515d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b5ee8ba-8578-4bda-8fc6-367838c9f23e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf72e28-ece2-46ac-a951-090fe77e7846</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58319805-d7e3-4314-a791-77fc09ec0199</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cff2c5-420f-406a-938f-0d5ee01a9da8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04fa9a67-7e92-44eb-95be-1b2d65624c5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62cb7c80-cb7a-4984-9833-94b04d47e6ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddb7ac68-2259-42b9-bab0-4c8ef62f170c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction without approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bb65a89-4991-4ac4-ab0d-f4ebb7a68e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc8481bc-8afc-408a-859d-51c1b4475238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ce9665-a4b5-4807-9d40-f3e984363171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c60e9480-8c35-4e91-bf1c-0565bb52dc1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>254a2d34-66bb-4070-949a-9f873f4bd330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ffd6140-38d1-4dc6-a079-ce4ed013288a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b93e0d42-0e26-4e69-832d-8f4ef696af5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9f57218-d72a-464c-aabb-f11e0e39a7a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a91399e3-f4c9-4017-9fde-7e7b1e7cbfb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction without approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4432c1-4590-4aec-a579-8777168e082e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b2bdded-b742-4e80-80ba-63a88d3579b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7148a158-588e-42db-83ee-9b38730c7171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e557783-f137-4752-a70a-cca5b154a9b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e728b30-3782-469e-8df4-bee2a1fa3d56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d37813-121d-483e-b9dc-ea9c967b4891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63cb619d-5c42-467f-a9c1-e1cf513354c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>095ea619-e2ef-46ef-8b20-05adb9db01fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0763289a-d5b3-4172-8be5-519f1044c03b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction without approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9bfeca8-a8f6-47eb-8727-4072f99161b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6009e873-9df8-454b-ad30-07121a8e0002</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58059f8f-3784-4a5d-94df-b1ba04fd353c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f26e0ca-a4be-4a1f-b3b0-01c737075b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff4dc6c7-9968-4ede-83e4-d5ca60f1d77a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51df88ae-edb1-48d7-a61e-5e4f88773b4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f8eb81d-d34b-4143-8881-69d5729269bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a763a41-7de0-4b6f-80ff-642918e7473e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f65b454-8106-493a-9513-673c1a75b015</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_De-register User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c8187138-d0ad-4ddb-ad41-db5862d6e527</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_NonAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd28f3ad-e669-4f64-968b-32375a829b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111cc5b6-35e9-4ee9-a67a-b822cdfdb437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>407d8473-e8b0-401d-b152-ecd818900b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c15603de-a8e2-4941-84cb-89f8564e9c2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Impuestos/Pago de Impuestos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e98643-da83-4592-97c9-2216f2387bf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74c7813-0ee3-428b-988d-a264f7c8b3dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfe6384-b6d8-419a-90ad-96756f318188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe8c8f73-c6ea-4917-ae38-8a05668c71c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb0deada-0c78-49b8-a35e-9383e931d81e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fc2e0af-3460-4fc7-8486-4ac40e0a7b0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Multi Currency/Pago de Préstamos - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e860300d-1e6d-4497-9ec3-6cbad6b32d8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48d1394f-73d8-412a-b097-a9837627c02d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2c6c008-cd09-4f05-8efe-8f1540d681ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>932f4639-8bad-4e08-97dc-7be04e6acd33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b77019-383b-4c12-ab1d-c369318e9bfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d1c4c5-42cd-4a9a-b919-296eac5a59a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5151670b-c26e-48b1-b366-f5d505b5b641</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f17910-95d7-4c8f-b80f-d17bed8f94e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad1b94c6-7bce-419b-8e3a-e5ecd4f786f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Multi Currency/Pago de Préstamos - Submit transaction with approval (From Dashboard Prestamo)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a51c50b-8ea3-42e2-9236-7b88d1f1ee47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571715a9-b32b-4d04-b180-031f0abbf899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d24b42a-e72d-45fe-83c5-d1acfcb9f22b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd8eb119-c5f6-4319-a4ed-97fe2ee2ecee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>981019f8-d213-4e35-93bc-17d108e6d107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e266c5-5b77-4d06-8a40-44573053660c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d31fefb2-70b8-42aa-9c3a-f3e0f37f9c8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69466df0-3db0-403b-8d53-da4ed13ae3fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77c4a7d7-d481-4f29-ba7e-d78b97322503</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Multi Currency/Pago de Préstamos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66965abb-d966-4c74-9792-905a0b9b17d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f49d5b00-7b11-477c-af4c-5a8c739bfaba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bcab118-2e48-42e2-8314-16b6e1ebf3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>743fee76-2896-4847-918e-4092a05c1351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>600d74cd-bfa0-403f-97c7-dd910d6fb727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>138ac8fd-bfa4-4efd-aa83-124764861beb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d645226-e0ce-45fa-88fb-56f65f6f426f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db105ea9-66f2-4ee1-b071-9edc6c38db28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e92a110-a099-4cfc-8cd6-bd8a7ccae386</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884ca6a4-8015-4ead-928c-799af517a343</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d06c806-3429-4169-85e3-2bef35815cb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b799ac-a04f-45ab-a8a2-b76c427e508a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>180469c9-250d-46bf-8d43-1c78c99f0ca9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a486f75-bd4b-43dd-bf1b-c78a8ad3fca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e301be5e-2ca9-4972-854b-001caa0e6727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cef14ab4-a31b-4cad-9db2-d63eae337bd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1576462a-3d9d-42aa-8726-0426e31c4cfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a03db75a-a96b-41e1-b41b-f2f24ab2cff8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction with approval (From Dashboard Prestamo)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a6c198-1fd6-4646-868a-8d2b95e9bce1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>380f7e2a-8ddf-4f30-92ad-673d550d784b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e5b70dd-ddd6-4df9-a2aa-c49691936705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>148da4a6-0cd8-4405-95f8-526133fb92e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81d4d2c6-f834-402a-a24b-561524450100</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f8c610d-886a-4bff-a805-393a1d37f03b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a39e447-7ac5-4640-94c2-a7c0ff76bd8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b154cfae-e13e-46e4-a248-c9a9db0b33bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2409473-fdb8-470a-88ed-ec9ab3797891</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Prestamo/Same Currency/Pago de Préstamos - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4225e14f-5820-48a2-8d0d-dad00a0151f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b905cc24-6d44-46af-860c-f74039a51ce1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecca641c-3766-4d78-8e6a-ee7336c60c8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412975a3-2cdd-4d6d-90a8-b17855ccd425</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fa7c8f-4088-490e-bc9b-cbf61d4cc80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebf69fa-ad46-4e15-a4c8-75159d9383c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70152408-9410-4e76-a045-1fcdbb4f644a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00364c08-e9aa-4565-85d6-c1a4036d0fcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de6d67fc-f7a9-4fb3-b261-fcf4a0cfd247</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b86ae66-f61b-440f-aff5-25dcb71d62cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca3700dc-5b34-410a-8490-2a452b6f24e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb713ab7-8127-491f-97eb-f76184c14490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1a8ab63-b092-4b61-ad59-e7b33cf50119</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12603284-b1b7-471f-b2c8-55aeb612f6d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c29de87-4de4-4536-892c-aff060c5550a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>355ad08c-2602-4a3e-ab55-ac7f6fa004d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed95afc-2713-47ec-a030-bb530925a95a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ae5ae94-2999-4af9-8ea6-2742eefe48d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21089a0f-2e03-4250-b06e-82e8d48c251c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf446887-2ee9-47b8-8d68-88f6cd78b0e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>788bea31-ec88-441e-97d6-d48cfc211de1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>212e0d2f-ebf5-42bb-836c-60d557dd0d62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b3fac5d-5dbb-4268-8eb3-e36c2814f0b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aee4c07-86a1-49cc-b53c-0bf2eaf94943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edec446a-8304-4b2f-b42f-961f28772e12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73c30888-a5b6-439e-967b-15c41637bef0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>127640c9-f52f-4d1f-a2d3-716bcb4ba984</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b92c38b0-054d-42df-b4e2-706359c8baba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89505493-f02d-4735-8517-9814a23cd13f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dacefcd8-3dc2-4bc0-8425-c6a56ffbfdee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20078727-03be-4989-97d8-3a91159f2e71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fea848d-6e07-4b28-b811-8f659f95331d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16182d73-fab9-4d7f-bbe2-8ed4e217a7ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9d679ea-1d88-4654-af21-3b884c1e2a55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d21f1b58-9072-4329-8b8d-5ec1efd98394</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a961f6b-ee98-4d85-94dd-2dceb5aa1d05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cec86fcb-3b0b-4cd2-b4de-a981cf0c29b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84bf3be8-7905-44a9-86f4-38013d2318b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a8e1852-cb6c-4981-8fd1-8b94fce2b4d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78296de-5896-4bb0-b716-481b4138b289</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7993595-944b-49b7-b0c6-7fe923389424</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f7ca546-3f1d-4b2d-8d18-d8719c747a5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48bbbadd-b7c7-41d3-ad88-e41af7628bff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09d7ec32-4ade-4818-871e-b876bba3ac0a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>355b1c08-598c-4645-a78a-4724f505947b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>796f1503-a4f3-4bf7-a8f2-f08c257bc4fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf60202-d802-4b67-a166-5b77be7f6db0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f63b96f-36d9-4090-9991-0a186ff3c627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a127c4-c33f-45d1-a316-5bdf208ead80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a2f399-1142-49c2-9bdb-2c022edda13f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>336b144a-5f0c-4f2b-bda8-fc4da5f72661</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0385fac-4555-4a8f-8aa1-d3808a6feb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d32fda33-008a-49d6-9413-500bfce2a94c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98a7450a-8a7e-45c9-8f87-44a542dad575</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Multi Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb557c4e-e008-4f8f-9890-80ffdaf4877a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0e8a5b5-a04c-4bbb-9846-d7ba5a6d3fd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bfcae45-5aee-4654-bc38-a43f9fc8ae3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12fc60c-039a-440c-bc18-be77ab1c10ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5810e1f3-c9bc-478a-a206-e73dc79ce43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d8e888-0d7d-4835-ae7f-35da1fe273dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27f77688-151a-44d8-a51d-e62acbbe152f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9840eaef-d050-4a84-9c7c-2650f91cb822</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de8e90e5-2440-431c-88ae-d7e0f02ebc26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52be9d63-cff2-44dd-9a00-b84ad12e7b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b246e0d-dcce-499a-a8c4-5dcdb7965d82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52bc3fe4-087e-4b91-916c-9b641746f5ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b513b59f-72d6-4b2e-995e-1264b94ae113</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9fba032-f632-4a96-9f2b-76e34fefe872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e64da83c-d769-4da6-ae87-0d79a9cab5b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e4cba0-6643-4010-bc3c-25c88cb75ce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3db3f368-4d79-4019-a6e2-fbeb54953d35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b788f294-1219-4037-a46e-36451591c3d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb44b2e-7117-45f6-85b4-98ebec89ede1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0cb7dfb-2af6-447e-b847-4a32ae9d659f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5d6fdf-df69-4d9e-b8b0-59086f88bf66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8feb4edf-5f92-4899-af89-6808f0ba866a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ad18c5-e7db-4071-a4f4-62362ac15ff3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76bafe82-62dc-4e30-9cf1-a559b1622972</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e34c2db8-4eb2-49c9-baf1-721eeb73652c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0b33b4-f8e4-4505-a25a-be5487a4893c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b43d28b7-6bf3-4fb9-befd-402a7f80fed6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Account Details)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31191da0-7929-495d-9b46-7549bdbce7f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b2e2d77-ff7d-4990-b28d-b86b6319045a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7964cdcc-3ea7-4aaf-9bb9-8c529471bb81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d785628b-d7bb-4beb-b3aa-cfe9dd2abf64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fabea92a-6036-4ff5-9e5a-71e788a6769b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33bb34e1-4ca2-40ea-bd31-423f3f0b69ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bade527-917e-482a-b5eb-2c20830ad0ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3138249-9e8d-4a14-8b00-7f17e45bea21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0109271-769b-4135-84c1-d5069d90c28d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Burger menu)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8869695f-6193-475f-a052-45d198dc1b13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1af4b62-5e53-4f6d-9d8f-03a07c0d56b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6eb3521-87a2-4ef6-bcff-661af7b60b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24fb81c4-f330-46ec-b74a-9bb30ab4c4a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d46f146-2f3b-4bc6-ae22-3ea55e3517e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51aa1545-3196-4f45-a740-a30735b2e654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20b136e-f062-4a20-b028-a62b4c78b315</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b653a8a3-d029-4a50-ab64-64ba62fa2106</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a37af24c-aee5-42b0-93f4-790707d550a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas FDR - Submit transaction with approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0db50b0c-c50c-4e50-9da4-e729983b978a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91d56c8-015b-4da5-a008-433e20ee3121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>436ed4b3-a453-4e4c-99b4-3d19703c2540</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3569a0ed-fb63-41ee-8ed3-0d6f307cc9a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b926d26b-093f-479b-8923-5a5be0d90847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fb64b15-43c5-4da4-b92d-57367efe9d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72c30257-7924-4913-89e7-68fa60ba5211</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5be18d1f-8e25-4622-8440-7cb016c24328</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe502c09-b139-46a5-8dca-cfe2a0ce80a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pagos/non admin/Tarjeta/Same Currency/Pagos a Tarjetas del Popular - Submit transaction with approval (From Dashboard Tarjeta)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1828f264-3745-4357-a06b-c8da97bb5e62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8b53c72-6889-4fda-b309-2cd2c195b721</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f0306dc-edfb-4a12-bceb-d90e461f4330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fbac67-800b-4efe-b148-b3ce5e7d4b15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b17594e4-2fed-4632-89d5-4ed24679cb1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57f1e2d9-b289-4d0d-b997-2dfb220801ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d488c2-34c5-4156-b85e-6dd906e05173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed891e1a-7e68-43bc-a679-e542385bea81</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
