<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression-Aprobaciones-Rechazos-Admin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9676f2ab-cf7a-4b89-b713-d4a2865c89d8</testSuiteGuid>
   <testCaseLink>
      <guid>96d42e2a-00b2-43ca-8fad-c3406651ad07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2dd5066-7aab-4622-9c9f-e93e6fdc6bae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f52e6bd7-9e64-448f-88fe-a60340f0e307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68f625f-0dc8-4266-945d-c507a36b985b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d195309c-9de5-4df4-8e72-a33a4108fe05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>810dab75-d847-419e-83b7-c156fe650cad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d282e9b9-5b65-4a42-a645-8c05773c0a66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8c2a513-ba18-489a-8666-5abc6f77fe31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>527cc230-ceb0-4738-bc02-360923063430</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f80bb54-39bf-4ee6-887e-285ae97b0568</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eed3987-39a3-4bbc-9321-323c417e3bfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f7d6a47-983a-4ab4-9405-874fc59c0fd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c1b5ce-44a1-48a9-b53e-80fff18211fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed6d65d3-97a3-47e0-97a4-8a2ba50935d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Impuesto - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288c30f9-eeea-4842-a351-ea5297897586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d45a9a-fd4c-4502-9294-205852b29214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0530d7-48fc-49e9-bc04-fdc392c245d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea531a18-be31-4b42-bc33-f8113217560d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35157172-bda6-4088-925d-31e417c49a9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2262ff17-7b6d-4d0d-9280-ebfc283ad6c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17bc95e-e344-44ca-98a5-431a9c95ef2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bf7ba9b-0f07-4a21-81b1-c59203d6a490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e881e84a-1171-4dfb-a2be-b3cbe44e207b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aba078ac-e39f-4ab0-999e-0e3af442c48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a90363c-b163-4569-9e50-8befd7828b55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6503acf9-ac0d-42e0-be7d-55207966d05e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6d31b6-ca62-440c-8c01-17b1a7a163dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7120954e-3c36-4e62-8d74-07ef80290308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc268fb-a202-4a05-b3ae-9727ea8b5495</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34167cb6-02ed-41f3-aff8-41a72786eadd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pago de Prestamos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cad55ca-2f1e-49bf-8d82-de05bdd40c8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d47a29-6925-473f-ad83-c3b2f2123ced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e646502f-355d-4786-bc05-347e5cabbd82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fb7f070-dbe8-4839-a866-0cd5a9c9e85d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6612ae93-370e-45aa-ad66-9b31aa7a2c14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6f6e6a-1a53-4900-a668-7ccfd68d2f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1718098f-0366-442f-9eef-09e48f935012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e0145c8-9702-43c4-9106-12dd32805173</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9415cae1-378e-4d63-bd0b-e28305aafbdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ae29c3-04a7-4b7e-aa95-5ab5135a3ac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e147433b-18ec-45d9-a7ef-b92e9d6927e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>602f3897-08d7-460f-b653-2b9e5b74286e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493784fb-7fb4-45a6-87e7-f4f146df701e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa068b2-89c3-4816-8570-02d7120391c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126fc9aa-b5da-4345-b9ef-882d9d969d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6627c5c4-3d49-4b6f-bea2-b471ffa4f93d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas del Popular - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5576e6de-a542-41ad-a0ce-f8788bf3ea56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8905e195-dc3c-4552-a40b-e7c28d13630a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742a647d-cbcf-4069-850a-b269850c5e93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc726ae6-4c77-498e-94a4-c95e2307e7a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7e0fd1-56d1-463d-a138-febf1a7185d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eddb0eb-2f3a-4cce-8bbf-4eb94cedde2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bb15204-41c0-4e14-98e0-ceae28e76bc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e794bdca-0f25-451f-ae28-657be558498d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b95ce6d2-0152-4f00-a9e2-f88304082c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05830ecd-35df-4bce-b10e-92a352999129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee991d7d-3c4a-4016-9790-7178a2f8617d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d58fa4dd-917a-4288-b68e-fbfc7160e255</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371bf4eb-4d60-4939-b2b3-05777f01dd57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47db51cc-a80e-4435-8327-7b49fbd1f6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40f3653-a31e-467b-8d35-a1172195192a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ab7347f-3f8e-4ee2-ad27-0be6b8c784cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta FDR Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b6017c-b6c5-4af3-bd0a-8fe4c3644a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ed6feb-72d3-435e-b2b0-19d299aa7ded</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd796fb7-7c7f-434d-bf1e-ae7307642b31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1ace919-13a0-476b-a837-f3067c76c2d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a302aa9a-c04d-494c-b630-83d0e834ea07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cf0cd74-c2d3-4255-ab14-fb42b998f1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f1d418-5c5c-49b4-82ff-7f1478373e4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fcd25c8-6595-4a4e-842e-f3c3700d2756</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50341392-cdb7-4c95-9af7-0c4a81cba203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a553b4-20b2-4baf-a304-edb8a8e20d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cd4c36-96f9-4cf1-98f4-7d4777ab2e0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6846522d-1ee6-4644-bde1-c76bcf1cf412</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8177568-b896-4449-8672-30f3f1f63136</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce5c775-75d9-4113-9e96-ef7b44656e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d36444-0632-4ee7-8944-e721b01f2725</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a4bc4ee-f039-4e95-b453-ab07497407ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias entre cuentas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0473ca4-5853-4b8d-b6ed-89bd94e98911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c906fb4-8fea-49f4-8fe8-14c647909e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e4c15dc-870d-409e-9e61-70efeee10ba7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>996cbf93-ee56-4a8d-be5a-65024ddb4113</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d58f2b1-7e42-4d03-bee3-62e9fa283a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65598a8-cebc-4c62-8e29-9e1d15cf3f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e3eabe-7cec-4daf-b26c-b62db914717b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>009ea6fc-2677-4602-ada4-917a11a55aee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dd448f3-7f5e-4978-b1c3-3f59f7bd2014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe6907e-8a53-402f-9443-aaa6311844d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abe4f6b-8ba0-4ff2-8b04-e1c331437074</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e8d6a8c-be72-46fb-a84d-90ac7bf0a49b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>898260f7-d217-4256-8c4c-f26df7b609e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b19755c-ad99-4c4e-8b9a-d52e1b0c017c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f1ac89c-96a0-4d9a-ba68-7c584050edc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d910563a-4077-4466-a5b1-1859b5294dd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios ACH - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8924610-c7e7-43ea-8dab-4e45ed64c520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cfa752-2977-47eb-b943-1fe547aa25ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452f5c07-7e6d-4a63-9cfa-5860c53a6db9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e979635-e66c-408c-967a-7fad7b38f25f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d3f646-c132-4a4f-bde4-7f74aca31867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcfd2cd-895a-4a15-9ed4-e0b4d826675d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b577b4-5ac7-4784-a54e-8f0a0fbf03e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80545bc3-03a9-4cea-af0a-5980e98deb0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4958e61a-454e-4dcd-be93-df1f5994af2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8f5237-04d8-42b7-8a28-3dc64d8037bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba4fb387-74e5-41eb-b235-e12b2285c116</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc1e2143-26a7-492a-93f9-4de9aa7f7f04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c82a92c-3bee-4a3c-88c6-45c5c13d463d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83eb501b-01aa-466c-a842-09ce27cad1cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1989de11-c2d5-445b-860b-a56c5925a480</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd4e2e35-e5ea-4e01-ba72-eed13bc6f3ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Transferencias cuentas de terceros (en BPD) - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f518ba5b-3211-4080-bddd-df1ae3b63515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>949d3ea3-353c-4720-a570-892c6472b886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd28be8c-af76-4569-b3e5-e2464ec067f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7793159-0668-4874-a2e8-bfb985dcf0b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6944eb-5c0b-4fd4-b5cb-be18fba7ffef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e117557-129d-4dd7-9f68-ec25a105b521</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9846dda6-f143-4795-ae5e-43d15b523b6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>290e0d3d-c705-4d38-bb53-dbf39a4fd75b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c30ed68f-c04d-4551-ac7f-dd06b898d011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85559751-e90a-4aec-b8e6-fe119ea16571</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e016ad-fd6d-4800-b47e-ea39f590f8b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e15e093e-ed57-4203-9373-794c9c8eb2f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf8b6449-12a5-4494-aa3b-8031ca7074b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc6bca0-c3ad-4c30-912b-c2f62ed1e8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fb63c8f-41e4-40ec-b85c-bbf4f9bbb158</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da0fd9d3-da6d-47f1-9a31-0e2fbfdc5bef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Desembolsos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823fd51e-e6d3-4816-972e-43e3ee8bb59d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6009164-ecb6-45de-80a5-efb8ea20fae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81dd6383-a970-471d-b578-0b95ac1b9275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4873c188-d748-4d2d-b35f-6b1027b72bfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f43fb9dc-429d-468e-8167-4427051bc699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>438bf64c-adfe-4535-a597-753e36a56579</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3f3c319-8945-4ce3-9c39-03e8e01770c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da5c0f56-1695-4d0f-b599-f02061d7b85a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88a34bef-f306-4ea4-8685-05a1db211f77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d6d0df9-217a-4611-a920-ef9f798e6ea4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd29075d-124c-4338-a6a4-16d53d41c775</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc0d64e1-d174-4293-98e3-f3b47e690e6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0eed897-821e-4c07-bc5d-76e89c2cae1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03adf14-b08f-4b23-9fb3-49876b01bf88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a7cd912-62d0-4dcd-b564-752629819e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12e0a3ae-e429-43e0-bf02-00039fd981ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Servicios y facturas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ecadd1f-f5d0-40ed-8f11-fb6abba4def0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42fec78-f441-409a-91b8-9dbae0e256f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a00edef-e76a-4f79-afd6-6ed9a15a6993</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65473fa-c488-4c98-8633-84a3654317bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8023b025-c9d6-46d6-bc2c-06d5ac3be4e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b24996-bf12-4443-8faa-a0c46f7995f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c02284b-642e-492e-9ea1-3eb8b610f37a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63e0e9bf-1aae-4f0e-87a0-894f9cf2d9b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e93cd4e-c3af-4c63-9fd3-d6619cfb616f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1437e41f-7999-4c9a-a547-4c98c8a4f943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b490ea-2b65-41e4-bad8-0e2c3db66ca4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6a038a9-238c-4d48-95ec-772e641c322a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3452814-0311-4208-9647-1c407ec70497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd42ee8f-00f9-4340-aa6e-a9df7010d891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b21e4b-783f-4b13-8708-38c41c671245</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6a9f713-ed71-4d32-9c4c-9995b935a8c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Mercado de Valores - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3879a14c-d666-4447-8da9-c2342c15f9bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6a5258b-0482-46f0-abe9-305d3571438a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f77d13-9e2a-4c1f-8a7c-f193bcb1d351</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a619beb4-c35e-466b-8397-4d59ee32b7e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c343c45b-1ac1-4793-bb6c-594d78e12029</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_De-register User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5d3d1413-3a72-4f98-8f98-9fda81289f56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/APPEMP_Registration_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78a204c-0e1b-4587-b5b8-c30cf04b5a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2949c840-c9b8-476a-aa9d-48beeff65dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75253ac2-652f-48c6-af41-f06a73835fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2213b45-72f6-469b-8abc-fc9da36fd78c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849088c8-b028-4cc3-8278-a34adab897b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c11b3f7d-258d-4478-85f3-05f72f73b2dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>420a82e3-f181-4f1e-ba4b-27646a7628c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31ec4c49-9296-44c2-9758-0f3ab8e2efb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d08add-fd5f-4040-ad44-8dc16ef354bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f30b1ff1-24bb-4b78-90fe-1a172d3050cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b1bec1-b956-4006-9886-e7961e1c51ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b810063-3a32-454e-bfab-aa03b3259f0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1d7aa4f-7a08-415f-a0d0-44d197a8f6db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbdf2ac0-2086-4100-a75f-19876ae902d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fbed9ba-485c-4098-a7da-135804ffae6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7475bc92-0f4c-4917-8664-531fd46e7f0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Pago de Prestamos - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b9ba2a-42b2-4136-b88f-fa6afbd1d4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c75382-d3d2-41cf-a226-6414d8b39866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be09dd65-549a-400c-9a3a-8fcf47be5867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc320443-00f9-4167-8b14-95fa393f4453</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0caa56-d3d9-4c54-8f55-a46480f1de9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a076830-6686-4f5b-9897-dd2ea5995c82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b12bf6-4913-4410-bb83-df04c70ea1f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82cccecf-f8b2-4309-a097-d428dedcef85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0bf3b9-f003-4a8b-a70d-07b11f7c82a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6460655-5d78-4924-857e-82dd39ac838f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc05dc2-a5bf-4a46-acc5-74a88fe5f330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>850a98a0-2fe8-4bc2-aa97-5784e4147267</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a946c47-78cf-4cd7-903f-a573cb44b48b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c86eb9c-d08e-45aa-86ac-0eedcca0c52a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e069694f-6e5d-4eb8-ae86-5ad1ec73495e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4198710-90a3-4a35-a928-bab0578376c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Tarjeta local Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a9a1cb1-8e23-483b-93c6-ea9a62c05b2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e042d2a-6346-4d7a-bd97-a0976fb35887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1140dfbe-a837-4495-ad63-eddefad6ab30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79c58424-42ce-463e-8544-ff2f1ad71fca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>673acf39-7a3c-4707-a7ed-45a52f044e00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a68dcd4-a562-437c-bccc-bf9bc8e0af8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e8acb43-afb3-4166-86c6-e98740716ecd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b95e4fb-0ef7-4b9e-94ce-3a425342b7e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87cf070-0b7c-4b6f-9c27-763e4f3e4469</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3d7c78-aea1-4cde-ba50-61f710bd48d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76988200-8c11-460d-9507-5156f68500d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c02dc2d-f82e-4e38-a48e-ae0b371e70e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b84b12-348e-4c91-b952-bde70369ab26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fc7c075-88df-4375-bc0f-1bffc1c83903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3636f4d6-8fab-4971-a60a-3c4713f44cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d7c50a8-6401-4d2a-8445-11a13845a5a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Pagos a Tarjetas FDR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>869d125a-f239-48cd-bd9e-023bc42a5f63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065ba68-ceb8-4bd1-a07e-0683620aa334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14482272-64bd-4d91-ae2e-f2e56be371dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6bd3050-3be2-4b73-9a86-7c1d06b88623</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcecb421-3276-48be-a4af-daad57d378e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc7987b-7cc1-483e-aca4-4c34fa7d7361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4479eb9-8831-4187-958a-5ff035d286b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf99e83c-6569-4030-95c8-1e8b588de98f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cfefeb9-2433-40c3-a5f8-66aa1bae33d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b53bb318-e940-4303-aff5-563aca6ea0dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00315e63-a93e-462c-9752-a2d41a2357d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64fb2b51-288b-46a5-9aa1-ddb5c9fa73f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d4e955b-18d2-479e-b335-b7845c82bc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01789308-15da-46d4-be8c-65a8cd299012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d782590-a3b0-45c3-ab46-70e3ec76214c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53b5ea99-e6a7-439d-b0bf-13569c668b37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Terceros Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ff0a41-aa52-472a-9a1e-76f0bfe4c4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce280073-7969-4923-9ea9-8f67506bad5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab928e9e-cd3b-4421-a6a1-200aa186244b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95e8e22e-6b09-4db6-a50b-ca22f29d3f99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5f80293-3ea5-4fcc-afc0-45bff68df807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d6fea8b-1e9f-4500-8a54-b78ab60c2cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7db8be4-75b7-44a6-99e5-3f112fcfa10f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a717cd94-3ba1-4904-b085-3825c9a0ecea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20dfcbe-cd47-40ad-92e5-0c2355497ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d16fba9-74c5-454f-8f9c-4ff0977b3480</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a8f42d-3aa2-4d36-88aa-6383e828bf1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9998f253-5528-4750-b4d6-100d8b8e50ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a966c47-82f5-4c63-98e0-6dd56c0784c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6005fd0d-295a-4f11-8653-f7414f308143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84d725f-dbc2-480d-a705-8d57c46cbc64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be8efef8-b3cd-45ba-944b-b7b9c6332397</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Interbancarios LBTR - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b29267-35fe-4a53-91f9-46f5b5b55121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d88669d-ee6d-4ba0-b2d5-97b841e64a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a6d77ea-70a7-4b00-9e46-ac874a7f1ebc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dccc56a-2854-412f-a7d9-c876a98d1518</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f443579-c940-4978-b5d6-b68cf64b685c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1026e239-b837-4602-aefa-d1637be13bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf28faf9-2a1c-43b2-8f1d-465f97d1811a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1233a03e-a2d6-4808-a652-02bcd4949ee8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4845520a-fcdb-44a5-b708-38c0a03fe593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e9c875-d714-42e7-a25c-c3ad09ba8c18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82daf827-6ca5-4672-8c0f-f6d7161e357c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f6b889c-6dd1-40da-a490-83934888c0e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da60edf-3c67-4ac7-a639-9e818158179b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ef94b9a-e406-44da-be0e-7a994847b3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ccaba82-30ac-4008-84ff-b69655780237</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bc2855f-9e25-481a-877f-9ab81aa11c08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Multicurrency Aprobaciones Cases/Entre mis cuentas Multi currency - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f55b1b7-3ff2-4a9b-9cf4-4a14f5a795b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cf57cb-0b67-493d-abc3-e42a054783a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dbfa71e-f05a-456a-ace4-eb20fa35b80e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af344461-8438-4ce4-94d7-a13230d2b97f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from burger menu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29539a93-417d-47bf-b0e9-10b6c0f63ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a15d660-8462-40da-a55c-490e76a91edf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e785d9-a2a0-4d77-946c-e3d99bc35ac3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc65deb3-1905-4324-9999-e539629c8702</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Aprobaciones detail verification from Dashboard bottom button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daa645d1-c041-4700-bc63-c33c951feed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e2c8af-8cfd-4fbb-add6-f205bb553b51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfea876-c7d0-41ec-ae8e-28610080766f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>013f82f6-b806-49d2-81c8-d88c9f5e05c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25f66fd-199b-4c68-8ff4-f34ca03e65c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24cb16bf-0b31-4374-a43d-49b1d9c17ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ada59a-974a-4831-9768-ef04cae87ae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d26a0b59-9a07-4bfc-bd5a-77b4830edf39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/All Payment - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>20e7bc4f-b109-418a-9b39-127d20b6960d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d64a7a-4be6-493c-af3f-a7c82437adcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7395da92-24ef-476a-b62d-abec0ce8acc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a92cd9-f04d-4e07-8d19-c6682396400d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b895882-147a-4125-978b-bca983c91d47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>add06736-d363-4232-ac32-1fd728cafc88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80098733-7e58-4d49-aa89-75c5b05130a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8b14de3-f291-4a6e-b74f-f2ec8a552c2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18dc0ec1-c8f4-47db-91b4-0ac190262c76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0980ecda-830f-4794-b936-1ef7cecfde1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9e22ae-4863-44d8-a4ea-dcf687b80b14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f876e5c-31f6-49ef-8fe6-5a7510b6a4eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5edc8603-4c58-495d-b727-39494bb83e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Nóminas - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df00eed-253a-40d7-bff0-924ecbcaf440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4413d35c-9ec7-4fec-8a71-a22a226be244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccdccb28-2230-417a-a443-c395588dd330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62f0b4df-a21b-451f-b9b5-3ca502cc8cae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Approve from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f356ae7c-22ef-42ce-9a45-8794a53dd323</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca98150b-93de-4a5f-87e9-b6dc43c503b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b3b3ee3-0e6a-4791-b810-81957b094c27</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de75d083-1c4e-49a9-b661-b723681776a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Approve from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa1d4120-e443-406b-b1f6-b0ee5b9acda8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fbefe8c-f413-479d-85cb-8d54f2d6af71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e829f733-1c56-435a-8f96-b9aa5e974b76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa8d6fcc-3663-43b5-a5b0-991ff1821445</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Reject from listing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1e16acc-fb20-4793-9ad3-5929ffbcae3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a688a92-b189-43d1-9c3d-9467942b6737</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6343f7d0-40fc-4704-90fc-6ce29440c243</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adaf7877-9a22-4c3a-bdd6-da9cdc65a9c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aprobaciones y rechazos/Suplidores - Reject from Transaction details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc2839a4-d297-42f0-8e51-d054bb3834ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3147bc9-e4ef-4865-9712-c0a3767c990b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b82766b3-08a2-48cf-8bbf-36bb4d193854</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
